server:
  port: 7005
spring:
  application:
    name: test
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
    gateway:
      ## gateway:discovery:locator:enabled:true这样就可以利用微服务名进行路由
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: url-proxy-1
#          uri: lb://bigdata
#          predicates:
#            - Path=/lsmfhx/bigdata/**
nacos:
  config:
    server-addr: 127.0.0.1:8848 #nacos的serverAdd配置
    group: DEFAULT_GROUP #分组的配置
    file-extension: json
    data-id: route-list #data-id的配置

